using UnityEngine;
using System.Collections.Generic;

///------------------------------------------------------------------------------<summary>
/// Base class for applying improvements and cleanup to raw node paths 
/// generated by a pathfinding algorithm. </summary>
public abstract class NodePathPostProcessor : MonoBehaviour //------------------------------------------------
{

    protected bool _showPostProcessingVisualizations = true;


    ///------------------------------------------------------------------------------<summary>
    /// 🔭 Nothing here yet... ✨   (description coming soon)   </summary>
    public abstract List<PathNode> GetNewPath(List<PathNode> controlPoints, Vector3 collisionBoxSize); //-----


    ///------------------------------------------------------------------------------<summary>
    /// 🔭 Nothing here yet... ✨   (description coming soon)   </summary>
    public abstract void Reset(); //----------------------------------------------------------


    ///------------------------------------------------------------------------------<summary>
    /// Sets the visibility of the in-editor debugging visualiations (Gizmos) for this
    /// postprocessor. (Requires Gizmos to be toggled ON in the viewport) </summary>
    public virtual void ShowDebuggingGizmos(bool newVisibility) //------------------------------------------
    {
        _showPostProcessingVisualizations = newVisibility;
    }
}